name: pr-preview

env:
  CONFIG_REPO_NAME: argocd-course-webapp-config

on:
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened, closed]

jobs:
  docker-build-push:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/argocd-course-webapp:pr-${{ github.event.pull_request.number }}

  update-config-repo:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Clone Argo CD config repo
        run: |
          git config --global user.email "ci-bot@argocd.com"
          git config --global user.name "ci-bot"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ env.CONFIG_REPO_NAME }}.git
          cd $CONFIG_REPO_NAME
          pr_path="apps/pr-${{ github.event.pull_request.number }}"
          mkdir -p apps/$pr_path
          cp $CONFIG_REPO_NAME/helm/webapp/values.yaml apps/$pr_path/values.yaml
          sed -i "s/^\( *pr_name: *\).*/\1pr-${pr_number}/" apps/${pr_path}/values.yaml
          git add .
          git commit -m "Add PR preview env for PR #${{ github.event.pull_request.number }}"
          git push

  cleanup-config:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Clone Argo CD config repo
        run: |
          git config --global user.email "ci-bot@argocd.com"
          git config --global user.name "ci-bot"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ env.CONFIG_REPO_NAME }}.git
          cd $CONFIG_REPO_NAME
          pr_path="apps/pr-${{ github.event.pull_request.number }}"
          rm -rf $pr_path
          git add -A
          git commit -m "Remove preview env for closed PR #${{ github.event.pull_request.number }}" || echo "No changes"
          git push
